### PR TITLE
Fix makefile problem

### PR DESCRIPTION
**Pull request by Jonathan50**
Fixes an issue with the makefile \(`-lncurses` should be after the sources/objects\)

### CODE REVIEW

**Comment by arthurdd** [comment]
It works fine for me under Debian and Arch Linux with gcc. What compiler are you using?

I'll merge it anyway just to be safe.

**Comment by Jonathan50** [comment]
`gcc` on Trisquel 7.0

Odd it's working for you.

**Comment by arthurdd** [comment]
yep, tested it on debian, arch, and os x.

maybe it's some ultra-libre version of gcc.

**Comment by Jonathan50** [comment]
No... it was the same on Ubuntu and gcc is by GNU so it will never have nonfree software

**Comment by arthurdd** [comment]
idk then. i merged it anyway.

**Comment by arthurdd** [comment]
I'm using gcc 5.3.0.

Which one are you using?

**Comment by Jonathan50** [comment]
4.8.4

**Comment by arthurdd** [comment]
That must be it then.

**Comment by Jonathan50** [comment]
Odd. And btw on Mac OS X your using clang, not gcc. `gcc` is a symlink to `clang`.

**Comment by jay4** [comment]
Ok

**Pull request merged**
